Mixin update for usercheckpoint
projectceladon/device-androidia pull request #1207
Opened 2021-06-29 08:36 UTC by vdanix

Mixin update for usercheckpoint patch

Change-Id: I4ac9ce24a6e584eda355f8c3c2750203d43b5faa
Tracked-On: OAM-97424
Signed-off-by: vdanix <vishwanathx.dani@intel.com>

2021-06-29 08:37 UTC, vdanix commented
Hi,
Kindly review the PR,

@JeevakaPrabu @sgnanase m.balaji@intel.com

2021-06-29 11:46 UTC, sgnanase approved these changes

2021-06-30 04:56 UTC, JeevakaPrabu requested changes

2021-06-30 04:56 UTC, JeevakaPrabu commented on caas/overlay/frameworks/base/core/res/res/values/config.xml
> +    </string-array>
Why is this change part of usercheckpoint patch?

2021-06-30 04:56 UTC, JeevakaPrabu commented on caas/extra_files/codecs/media_codecs_gen9.xml
>          <MediaCodec name="OMX.Intel.hw_vd.h264" type="video/avc" >
Why is line removal change part of this patch?

2021-06-30 04:56 UTC, JeevakaPrabu commented on caas/extra_files/codecs/mfx_omxil_core.conf
>  OMX.Intel.hw_ve.h264 : libmfx_omx_components_hw.so
Why is line removal change part of this patch?

2021-06-30 04:56 UTC, JeevakaPrabu commented on celadon_tablet/extra_files/codecs/mfx_omxil_core.conf
>  OMX.Intel.hw_ve.h264 : libmfx_omx_components_hw.so
Why is line removal change part of this patch?

2021-06-30 12:50 UTC, closed without merging