Fix: typo CONFIG_KPROBE_EVENT to CONFIG_KPROBE_EVENTS in debug_diffconfig
projectceladon/device-androidia pull request #1663
Opened 2023-06-01 02:22 UTC by sunausti

Fix: typo CONFIG_KPROBE_EVENT to CONFIG_KPROBE_EVENTS in debug_diffconfig
Tracked-On: OAM-110550

2023-06-01 05:30 UTC, sysopenci commented
Expected syntax:
    Commit message one-line summary

      Extra paragraphs can be added here.

      Longer description that explains the problem / solution
      or whatever that needs to be said

      It can contain
        multiple lines
        multiple paragraphs
        blank lines
        references

      But each paragraph must be followed by a blank line

      However, you need to keep the 'Tracked-On', 'Change-Id',
      'Signed-off-by', ..., fields in the **lastest** paragraph of
      the commit message.

      Change-Id: I9e58f79c7faf7f0edb9792e8b5322ab161331141
      Tracked-On: https://jira.server.ext/browse/PROJECTA-123
      Signed-off-by: Developer Name <developer.name@intel.com>

2023-06-02 09:14 UTC, kaushlen approved these changes

2023-06-02 11:01 UTC, JeevakaPrabu requested changes
please provide the changes in this project https://github.com/projectceladon/device-androidia-mixins

2023-06-02 14:45 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/89

2023-06-03 00:50 UTC, sunausti commented
> please provide the changes in this project https://github.com/projectceladon/device-androidia-mixins

https://github.com/projectceladon/device-androidia-mixins/pull/1654 this is the mixins fix

2023-06-05 00:41 UTC, sunausti commented
Close this PR as https://github.com/projectceladon/device-androidia-mixins/pull/1654 was merged, and auto propagated

2023-06-05 00:41 UTC, closed without merging